"""`-mtune=` values selectable via `//constraints/mtune`."""

# Each entry declares a constraint_value named after the string passed to
# `-mtune=`. Values are architecture-specific; a platform is responsible for
# pairing one with a compatible `@platforms//cpu`.
MTUNES = [
    "generic",
    # x86-64, Intel P-cores.
    "nehalem",
    "westmere",
    "sandybridge",
    "ivybridge",
    "haswell",
    "broadwell",
    "skylake",
    "skylake-avx512",
    "cascadelake",
    "cooperlake",
    "icelake-client",
    "icelake-server",
    "rocketlake",
    "tigerlake",
    "alderlake",
    "raptorlake",
    "meteorlake",
    "arrowlake",
    "lunarlake",
    "pantherlake",
    "sapphirerapids",
    "emeraldrapids",
    "graniterapids",
    "graniterapids-d",
    "diamondrapids",
    # x86-64, Intel E-cores.
    "silvermont",
    "goldmont",
    "goldmont-plus",
    "tremont",
    "gracemont",
    "sierraforest",
    "grandridge",
    "clearwaterforest",
    # x86-64, AMD.
    "znver1",
    "znver2",
    "znver3",
    "znver4",
    "znver5",
    # AArch64, Arm Neoverse.
    "neoverse-e1",
    "neoverse-n1",
    "neoverse-n2",
    "neoverse-n3",
    "neoverse-v1",
    "neoverse-v2",
    "neoverse-v3",
    "neoverse-v3ae",
    "neoverse-512tvb",
    # AArch64, Arm Cortex-X.
    "cortex-x1",
    "cortex-x2",
    "cortex-x3",
    "cortex-x4",
    "cortex-x925",
    # AArch64, other implementations.
    "a64fx",
    "ampere1",
    "ampere1a",
    "ampere1b",
    "ampere1c",
    "cobalt-100",
    "grace",
    "oryon-1",
    "tsv110",
    # AArch64, Apple.
    "apple-m1",
    "apple-m2",
    "apple-m3",
    "apple-m4",
    # AArch64, Arm Cortex-A.
    "cortex-a35",
    "cortex-a53",
    "cortex-a55",
    "cortex-a57",
    "cortex-a72",
    "cortex-a73",
    "cortex-a75",
    "cortex-a76",
    "cortex-a77",
    "cortex-a78",
    "cortex-a510",
    "cortex-a520",
    "cortex-a710",
    "cortex-a715",
    "cortex-a720",
    "cortex-a725",
    # armv7 Arm Cortex-A.
    "cortex-a5",
    "cortex-a7",
    "cortex-a8",
    "cortex-a9",
    "cortex-a12",
    "cortex-a15",
    "cortex-a17",
    "cortex-a32",
]
