# Emits the libstdc++ config.h model from the checks selected by
# //runtimes/libstdcxx/autoconf:configure_ac_checks.bzl. Generic CC probe
# execution lives in //runtimes/libstdcxx/autoconf:cc_configure_probe.bzl.

load(
    "//runtimes/libstdcxx/autoconf:cc_configure_probe.bzl",
    "cc_configure_probe_context",
    "cc_configure_probe_toolchains",
    "cc_configure_probe_transition",
    "declare_compile_probe",
    "declare_link_probe",
    "policy_result",
)
load("//runtimes/libstdcxx/autoconf:configure_ac_checks.bzl", "COMPILE_CHECKS", "LINK_CHECKS", "POLICY_DEFINES")

_GTHREAD_CONTEXT_CHECKS = {
    "_GLIBCXX_HAS_GTHREADS": True,
    "_GLIBCXX_USE_PTHREAD_RWLOCK_T": True,
}

def _gthr_include_root(ctx):
    for file in ctx.files.gthr_headers:
        if file.basename == "gthr.h":
            if not file.dirname.endswith("/bits"):
                fail("expected generated gthr.h under a bits directory")
            return file.dirname[:-len("/bits")]
    fail("generated gthr headers do not contain bits/gthr.h")

def _probe_extra_inputs_and_flags(ctx, check):
    if _GTHREAD_CONTEXT_CHECKS.get(check.name, False):
        return (ctx.files.gthr_headers, ["-I" + _gthr_include_root(ctx)])
    return ([], [])

def _write_config_outputs(ctx, config_h, summary, results):
    arguments = [
        config_h.path,
        summary.path,
        ctx.attr.host_triple,
        ctx.attr.cpu_include_dir,
        ctx.attr.os_include_dir,
        ctx.attr.abi_baseline_pair,
        ctx.attr.abi_tweaks_dir,
        ctx.attr.atomicity_dir,
        ctx.attr.atomic_word_dir,
        "1" if ctx.attr.atomic_lock_policy else "0",
        ctx.attr.cpu_defines_dir,
        ctx.attr.error_constants_dir,
        ctx.attr.symver_style,
    ]
    inputs = []
    for result in results:
        result_path = ""
        if result.result:
            result_path = result.result.path
            inputs.append(result.result)
        arguments.extend([
            result.check.name,
            result.kind,
            getattr(result.check, "language", "policy"),
            getattr(result.check, "value", ""),
            result_path,
            ",".join(getattr(result.check, "defines_on_success", [])),
        ])

    ctx.actions.run_shell(
        inputs = inputs,
        outputs = [config_h, summary],
        arguments = arguments,
        command = """set -eu
config_h="$1"
summary="$2"
host_triple="$3"
cpu_include_dir="$4"
os_include_dir="$5"
abi_baseline_pair="$6"
abi_tweaks_dir="$7"
atomicity_dir="$8"
atomic_word_dir="$9"
atomic_lock_policy="${10}"
cpu_defines_dir="${11}"
error_constants_dir="${12}"
symver_style="${13}"
shift 13
tmp="${TMPDIR:-/tmp}/libstdcxx-config-output-$$"
mkdir -p "$tmp"
trap 'rm -rf "$tmp"' EXIT
checks_json="$tmp/checks.json"
: > "$checks_json"

{
    echo "/* Generated by @llvm//runtimes/libstdcxx:config_h. */"
    echo "#ifndef LLVM_LIBSTDCXX_CONFIG_H"
    echo "#define LLVM_LIBSTDCXX_CONFIG_H 1"
    if [ "$symver_style" = "gnu" ]; then
        echo "#define _GLIBCXX_SYMVER 1"
        echo "#define _GLIBCXX_SYMVER_GNU 1"
        echo "#define HAVE_AS_SYMVER_DIRECTIVE 1"
        echo "#define HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT 1"
        echo "#define HAVE_EXCEPTION_PTR_SINCE_GCC46 1"
    fi
    if [ "$atomic_lock_policy" = "1" ]; then
        echo "#define HAVE_ATOMIC_LOCK_POLICY 1"
    fi
    json_defines_for_result() {
        json_defines=""
        if [ "$defines_on_success" != "$name" ]; then
            json_defines=', "defines_on_success": ['
            define_comma=""
            old_ifs="$IFS"
            IFS=","
            for define_name in $defines_on_success; do
                json_defines="${json_defines}${define_comma}\\"${define_name}\\""
                define_comma=", "
            done
            IFS="$old_ifs"
            json_defines="${json_defines}]"
        fi
    }
    comma=""
    while [ "$#" -gt 0 ]; do
        name="$1"
        kind="$2"
        language="$3"
        value="$4"
        result_file="$5"
        defines_on_success="$6"
        shift 6
        if [ "$kind" = "define" ]; then
            json_defines_for_result
            old_ifs="$IFS"
            IFS=","
            for define_name in $defines_on_success; do
                echo "#define $define_name $value"
            done
            IFS="$old_ifs"
            printf '%s    "%s": {"kind": "%s", "value": "%s"%s}' "$comma" "$name" "$kind" "$value" "$json_defines" >> "$checks_json"
        elif [ "$kind" = "string_define" ]; then
            echo "#define $name \\\"$value\\\""
            printf '%s    "%s": {"kind": "%s", "value": "%s"}' "$comma" "$name" "$kind" "$value" >> "$checks_json"
        elif [ "$kind" = "undef" ]; then
            echo "/* #undef $name */"
            printf '%s    "%s": {"kind": "%s"}' "$comma" "$name" "$kind" >> "$checks_json"
        else
            result="$(cat "$result_file")"
            json_defines_for_result
            old_ifs="$IFS"
            IFS=","
            if [ "$result" = true ]; then
                for define_name in $defines_on_success; do
                    echo "#define $define_name 1"
                done
            else
                for define_name in $defines_on_success; do
                    echo "/* #undef $define_name */"
                done
            fi
            IFS="$old_ifs"
            printf '%s    "%s": {"kind": "%s", "ok": %s, "language": "%s"%s}' "$comma" "$name" "$kind" "$result" "$language" "$json_defines" >> "$checks_json"
        fi
        comma=",
"
    done
    echo "#endif"
} > "$config_h"

{
    echo "{"
    echo "  \\"host_triple\\": \\"$host_triple\\","
    echo "  \\"cpu_include_dir\\": \\"$cpu_include_dir\\","
    echo "  \\"os_include_dir\\": \\"$os_include_dir\\","
    echo "  \\"abi_baseline_pair\\": \\"$abi_baseline_pair\\","
    echo "  \\"abi_tweaks_dir\\": \\"$abi_tweaks_dir\\","
    echo "  \\"atomicity_dir\\": \\"$atomicity_dir\\","
    echo "  \\"atomic_word_dir\\": \\"$atomic_word_dir\\","
    echo "  \\"atomic_lock_policy\\": $atomic_lock_policy,"
    echo "  \\"cpu_defines_dir\\": \\"$cpu_defines_dir\\","
    echo "  \\"error_constants_dir\\": \\"$error_constants_dir\\","
    echo "  \\"symver_style\\": \\"$symver_style\\","
    echo "  \\"checks\\": {"
    cat "$checks_json"
    echo
    echo "  }"
    echo "}"
} > "$summary"
""",
        execution_requirements = {"supports-path-mapping": "1"},
        mnemonic = "LibstdcxxConfigProbe",
    )

def _libstdcxx_config_h_impl(ctx):
    config_h = ctx.actions.declare_file(ctx.attr.name + ".h")
    summary = ctx.actions.declare_file(ctx.attr.name + ".json")
    probe_context = cc_configure_probe_context(
        ctx = ctx,
        source_placeholder = "__libstdcxx_probe_source__.c",
        object_placeholder = "__libstdcxx_probe_output__.o",
        binary_placeholder = "__libstdcxx_probe_binary__",
    )

    results = []
    for check in COMPILE_CHECKS:
        extra_inputs, extra_flags = _probe_extra_inputs_and_flags(ctx, check)
        results.append(declare_compile_probe(
            ctx = ctx,
            probe_context = probe_context,
            check = check,
            extra_inputs = extra_inputs,
            extra_flags = extra_flags,
        ))
    for check in LINK_CHECKS:
        extra_inputs, extra_flags = _probe_extra_inputs_and_flags(ctx, check)
        results.append(declare_link_probe(
            ctx = ctx,
            probe_context = probe_context,
            check = check,
            extra_inputs = extra_inputs,
            compile_extra_flags = extra_flags,
        ))
    for policy in POLICY_DEFINES:
        results.append(policy_result(policy))

    _write_config_outputs(ctx, config_h, summary, results)

    return [
        DefaultInfo(files = depset([config_h, summary])),
        OutputGroupInfo(
            config_h = depset([config_h]),
            summary = depset([summary]),
        ),
    ]

libstdcxx_config_h = rule(
    implementation = _libstdcxx_config_h_impl,
    attrs = {
        "abi_baseline_pair": attr.string(mandatory = True),
        "abi_tweaks_dir": attr.string(mandatory = True),
        "atomic_lock_policy": attr.bool(mandatory = True),
        "atomic_word_dir": attr.string(mandatory = True),
        "atomicity_dir": attr.string(mandatory = True),
        "cpu_defines_dir": attr.string(mandatory = True),
        "cpu_include_dir": attr.string(mandatory = True),
        "error_constants_dir": attr.string(mandatory = True),
        "gthr_headers": attr.label(allow_files = True, mandatory = True),
        "host_triple": attr.string(mandatory = True),
        "os_include_dir": attr.string(mandatory = True),
        "symver_style": attr.string(default = "none"),
    },
    cfg = cc_configure_probe_transition,
    fragments = ["cpp"],
    toolchains = cc_configure_probe_toolchains,
)
