# Emits the libstdc++ config.h model from the checks selected by
# //runtimes/libstdcxx/autoconf:configure_ac_checks.bzl. Generic CC probe
# execution lives in //runtimes/libstdcxx/autoconf:cc_configure_probe.bzl.

load(
    "//runtimes/libstdcxx/autoconf:cc_configure_probe.bzl",
    "cc_configure_probe_context",
    "cc_configure_probe_toolchains",
    "cc_configure_probe_transition",
    "declare_compile_probe",
    "declare_link_probe",
    "policy_result",
)
load("//runtimes/libstdcxx/autoconf:configure_ac_checks.bzl", "COMPILE_CHECKS", "LINK_CHECKS", "POLICY_DEFINES")

_GTHREAD_CONTEXT_CHECKS = {
    "_GLIBCXX_HAS_GTHREADS": True,
    "_GLIBCXX_USE_PTHREAD_RWLOCK_T": True,
}

def _gthr_include_root(ctx):
    for file in ctx.files.gthr_headers:
        if file.basename == "gthr.h":
            if not file.dirname.endswith("/bits"):
                fail("expected generated gthr.h under a bits directory")
            return file.dirname[:-len("/bits")]
    fail("generated gthr headers do not contain bits/gthr.h")

def _probe_extra_inputs_and_flags(ctx, check):
    if _GTHREAD_CONTEXT_CHECKS.get(check.name, False):
        return (ctx.files.gthr_headers, ["-I" + _gthr_include_root(ctx)])
    return ([], [])

def _write_config_output(ctx, config_h, results):
    arguments = [
        config_h.path,
        "1" if ctx.attr.atomic_lock_policy else "0",
        ctx.attr.symver_style,
    ]
    inputs = []
    for result in results:
        result_path = ""
        if result.result:
            result_path = result.result.path
            inputs.append(result.result)
        arguments.extend([
            result.check.name,
            result.kind,
            getattr(result.check, "value", ""),
            result_path,
            ",".join(getattr(result.check, "defines_on_success", [])),
        ])

    ctx.actions.run_shell(
        inputs = inputs,
        outputs = [config_h],
        arguments = arguments,
        command = """set -eu
config_h="$1"
atomic_lock_policy="$2"
symver_style="$3"
shift 3

{
    echo "/* Generated by @llvm//runtimes/libstdcxx:config_h. */"
    echo "#ifndef LLVM_LIBSTDCXX_CONFIG_H"
    echo "#define LLVM_LIBSTDCXX_CONFIG_H 1"
    if [ "$symver_style" = "gnu" ]; then
        echo "#define _GLIBCXX_SYMVER 1"
        echo "#define _GLIBCXX_SYMVER_GNU 1"
        echo "#define HAVE_AS_SYMVER_DIRECTIVE 1"
        echo "#define HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT 1"
        echo "#define HAVE_EXCEPTION_PTR_SINCE_GCC46 1"
    fi
    if [ "$atomic_lock_policy" = "1" ]; then
        echo "#define HAVE_ATOMIC_LOCK_POLICY 1"
    fi
    while [ "$#" -gt 0 ]; do
        name="$1"
        kind="$2"
        value="$3"
        result_file="$4"
        defines_on_success="$5"
        shift 5
        if [ "$kind" = "define" ]; then
            old_ifs="$IFS"
            IFS=","
            for define_name in $defines_on_success; do
                echo "#define $define_name $value"
            done
            IFS="$old_ifs"
        elif [ "$kind" = "string_define" ]; then
            echo "#define $name \\\"$value\\\""
        elif [ "$kind" = "undef" ]; then
            echo "/* #undef $name */"
        else
            result="$(cat "$result_file")"
            old_ifs="$IFS"
            IFS=","
            if [ "$result" = true ]; then
                for define_name in $defines_on_success; do
                    echo "#define $define_name 1"
                done
            else
                for define_name in $defines_on_success; do
                    echo "/* #undef $define_name */"
                done
            fi
            IFS="$old_ifs"
        fi
    done
    echo "#endif"
} > "$config_h"
""",
        execution_requirements = {"supports-path-mapping": "1"},
        mnemonic = "LibstdcxxConfigProbe",
    )

def _libstdcxx_config_h_impl(ctx):
    config_h = ctx.actions.declare_file(ctx.attr.name + ".h")
    probe_context = cc_configure_probe_context(
        ctx = ctx,
        source_placeholder = "__libstdcxx_probe_source__.c",
        object_placeholder = "__libstdcxx_probe_output__.o",
        binary_placeholder = "__libstdcxx_probe_binary__",
    )

    results = []
    for check in COMPILE_CHECKS:
        extra_inputs, extra_flags = _probe_extra_inputs_and_flags(ctx, check)
        results.append(declare_compile_probe(
            ctx = ctx,
            probe_context = probe_context,
            check = check,
            extra_inputs = extra_inputs,
            extra_flags = extra_flags,
        ))
    for check in LINK_CHECKS:
        extra_inputs, extra_flags = _probe_extra_inputs_and_flags(ctx, check)
        results.append(declare_link_probe(
            ctx = ctx,
            probe_context = probe_context,
            check = check,
            extra_inputs = extra_inputs,
            compile_extra_flags = extra_flags,
        ))
    for policy in POLICY_DEFINES:
        results.append(policy_result(policy))

    _write_config_output(ctx, config_h, results)

    return [
        DefaultInfo(files = depset([config_h])),
        OutputGroupInfo(
            config_h = depset([config_h]),
        ),
    ]

libstdcxx_config_h = rule(
    implementation = _libstdcxx_config_h_impl,
    attrs = {
        "atomic_lock_policy": attr.bool(mandatory = True),
        "gthr_headers": attr.label(allow_files = True, mandatory = True),
        "symver_style": attr.string(default = "none"),
    },
    cfg = cc_configure_probe_transition,
    fragments = ["cpp"],
    toolchains = cc_configure_probe_toolchains,
)
