load("@rules_cc//cc/toolchains:args.bzl", "cc_args")
load("@rules_cc//cc/toolchains/impl:documented_api.bzl", "cc_args_list")

package(default_visibility = ["//toolchain/args/windows:__pkg__"])

cc_args(
    name = "header_sysroot",
    actions = [
        "//toolchain:source_compile_actions",
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    allowlist_include_directories = ["//toolchain/headers:mingw"],
    args = ["--sysroot={headers}"],
    data = ["//toolchain/headers:mingw"],
    format = {"headers": "//toolchain/headers:mingw"},
)

cc_args(
    name = "default_library_search_paths",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "-L{mingw_import_library_search_path}",
        "-L{mingw_crt_library_search_path}",
    ],
    data = [
        "//runtimes/mingw:mingw_crt_library_search_directory",
        "//runtimes/mingw:mingw_import_libraries_directory",
    ],
    format = {
        "mingw_crt_library_search_path": "//runtimes/mingw:mingw_crt_library_search_directory",
        "mingw_import_library_search_path": "//runtimes/mingw:mingw_import_libraries_directory",
    },
)

cc_args(
    name = "deterministic_link_flags",
    actions = ["@rules_cc//cc/toolchains/actions:link_actions"],
    args = ["-Wl,--no-insert-timestamp"],
)

cc_args_list(
    name = "default_libs",
    args = [
        "default_library_search_paths",
    ] + select({
        "//constraints/windows/crt:msvcrt": ["msvcrt_default_libs"],
        "//constraints/windows/crt:ucrt": ["ucrt_default_libs"],
    }),
)

cc_args(
    name = "msvcrt_default_libs",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    # msvcrt.dll plus compatibility objects provided by mingw-w64.
    args = [
        "-lmsvcrt_common",
        "-lmsvcrt_extra",
        "-lmsvcrt",
    ],
)

cc_args(
    name = "ucrt_default_libs",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = ["-lucrt"],
)

cc_args_list(
    name = "sysroot_flags",
    args = select({
        "//toolchain:hosted_headers": ["header_sysroot"],
        "//conditions:default": ["//toolchain/args:empty_sysroot_flags"],
    }),
)
